### ISSUE TITLE
Single Line Comments aren't grayed out

### ISSUE THREAD

**Issue by mdw7326** [corbanmailloux/sublime-promela-spin#4]
A single line comment in promela isn't grayed out like a comment should be.
Reminder, promela single line comment is `//`

**Comment by corbanmailloux** [comment]
Can you point me to where that is in the Promela spec? I couldn't find it when I was building this, hence [this block](https://github.com/corbanmailloux/sublime-promela-spin/blob/master/Syntaxes/Promela.YAML-tmLanguage#L95).

**Comment by corbanmailloux** [comment]
There's [this](http://spinroot.com/spin/Man/comments.html), but it only mentions block comment format.

**Comment by mdw7326** [comment]
Fair enough, it doesn't appear to be documented.  But the compiler does treat it as a comment.

**Comment by corbanmailloux** [comment]
Really? Neat.
If you've tested it and can confirm that the compiler handles it, I might add it. I just want to stay true to the spec.

**Comment by mdw7326** [comment]
Ya, it totally gets handled by the compiler. But that could be because promela actually uses a C compiler. But all C compilers handle the single line comment. So, I'd say take it or leave it, but I just wanted to bring it to your attention.

**Comment by corbanmailloux** [comment]
Closed with PR #5
